In [16]:
import numpy as np
from einops import repeat
from torch import torch

In [2]:
rng = np.random.default_rng()

In [3]:
rng.integers(5, size=(8, 4))

array([[4, 1, 2, 2],
       [4, 2, 1, 3],
       [1, 0, 1, 4],
       [0, 4, 4, 0],
       [1, 1, 0, 0],
       [0, 4, 2, 1],
       [3, 3, 0, 0],
       [0, 1, 4, 2]])

In [5]:
x = np.arange(64)

In [6]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [10]:
repeated = repeat(x, 'd -> repeat d', repeat=8)

In [11]:
repeated.shape

(8, 64)

In [14]:
rng.permuted(repeated, axis=1)

array([[22, 43, 45,  0, 36, 52, 29,  9, 44, 57, 30, 39, 49, 14, 40, 15,
        53,  3, 50, 21, 60, 17, 59, 34, 26,  7, 28, 35, 41, 48, 31, 61,
        37, 12, 51, 16, 24, 63, 13, 27,  1, 32, 46,  5, 38, 55, 18,  2,
        56, 11, 20, 58,  8, 19,  4, 47,  6, 33, 25, 10, 54, 62, 42, 23],
       [60, 29, 35, 51, 40, 46, 12, 18, 11, 42, 28, 30, 10,  0, 50, 58,
        15,  3, 22,  2, 49, 54, 31, 62, 19, 32, 24, 55,  6, 53,  4, 52,
         8,  5, 17,  9, 39, 36, 63, 48, 61, 16, 26, 23, 34, 45,  7, 38,
        13, 21, 57, 20, 43, 33, 47, 59, 25, 41, 56, 44,  1, 27, 37, 14],
       [ 5, 21, 51, 43, 58, 11, 44,  0, 17, 62, 57, 42, 12, 31, 45, 35,
        27, 55, 59, 48, 23,  2, 37,  1, 13, 22, 61, 41,  3,  6, 40, 33,
         9, 28, 10, 18, 30, 32, 47, 54, 39, 15, 25,  8, 24, 26, 52, 50,
        14, 19,  4, 60, 56, 63, 38, 20, 16, 53, 34, 49, 46,  7, 29, 36],
       [42, 38, 15, 33, 21,  4, 36, 20, 16, 14, 37, 59, 47, 32,  6, 55,
        22,  9,  1, 46,  2, 29, 53, 56, 61, 52, 27, 17, 30, 2

In [62]:
a = torch.tensor([[[3,2,1],[1,3,2]]])

In [63]:
a

tensor([[[3, 2, 1],
         [1, 3, 2]]])

In [57]:
a.shape

torch.Size([1, 2, 3])

In [65]:
i = torch.tensor([[[2,1,0],[0,2,1]]])

In [69]:
i.squeeze(0).shape

torch.Size([2, 3])

In [68]:
i.

tensor([[[2, 1, 0],
         [0, 2, 1]]])

In [70]:
c = torch.zeros_like(a)

In [73]:
c

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [74]:
c.shape

torch.Size([1, 2, 3])

In [75]:
c[0]

tensor([[0, 0, 0],
        [0, 0, 0]])

torch.Size([1, 1, 1, 3])